export const PHONE_NOT_AVAILABLE = 'PHONE NOT AVAILABLE';
export const TWITTER_NOT_AVAILABLE = 'TWITTER NOT AVAILABLE';
export const ADDRESS_NOT_AVAILABLE = 'ADDRESS NOT AVAILABLE';
export const CROSS_STREET_NOT_AVAILABLE = 'CROSS STREET NOT AVAILABLE';
export const NOT_AVAILABLE = 'NOT_AVAILABLE';
export const CODE_NOT_AVAILABLE = 'CODE_NOT_AVAILABLE'
export const STATE_NOT_AVAILABLE = 'STATE_NOT_AVAILABLE';